### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by icyfox168168** [Sokolmish/diploma#1]

**Comment by Sokolmish** [comment]
Theoretically, there are no serious obstacles to compile it on Windows. I know following minor reasons.

- Flex should be used with `nounistd` option
- There is Unix-specific methods to write binary data to stdout. It is disabled by `#ifdef __unix__`, but I should check if it has been done properly (e.g. some includes)
- Subprocess library is declared as cross-platform, but I haven't check this. Anyway, subprocessing also can be disabled, as I consider LLVM IR as a main result of the compiler
- There are GNU-specific options in CMake: `-Wall -Wextra -Wno-unused-parameter`. I think, them can be disabled by some ifs.

I will try to fix these issues in near future. But I don't sure, if I can build this on Windows, because of lack of experience with programming on Windows, especially with libraries handling.
